### ISSUE TITLE
Function MEMORY not supported on Mac (&Linux?)

### ISSUE THREAD

**Issue by jhohlbein** [BiteenMatlab/SMALL-LABS#1]
SMALL-LABS throws an error due to an unsupported memory function on Matlab for Mac (probably on Linux as well). The function is used in Movie2mat.m.

**Comment by stephenalee** [comment]
Hi jhohlbein,

Can you provide the specific line for where the error is occurring. Also, what is the file format of the movie you are running?

Thank you

**Comment by jhohlbein** [comment]
Not sure I understand the question. The function itself is not supported under Mac/Linux, so when Small-labs is trying to call it, it'll throw an error. File format is tiff.

On 29 Aug 2019 9:55 pm, Stephen A Lee <notifications@github.com> wrote:

Hi jhohlbein,

Can you provide the specific line for where the error is occurring. Also, what is the file format of the movie you are running?

Thank you

**Comment by stephenalee** [comment]
I understand now. The function movie2mat.m has been updated to avoid this problem.

Thank you for bring it to our attention.
